artifacts:
  ARTIFACTS_DIR : artifacts
  PREPARE_DATA: prepared
  MODEL_FEATURES: model_features
  FEATURE_TRAIN_DATA: train.pkl
  FEATURE_TEST_DATA: test.pkl
  PIPELINE_DATA: pipeline.pkl
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv

local_data_file_path: 'data.xml'
split_ratio : 0.3

featurization:
  max_features: 2500
  norms: 2